### ISSUE TITLE
Raspberry PI - issue when requireing node-microphone

### ISSUE THREAD

**Issue by spoggie** [Flowr-es/node-microphone#2]
On Raspberry PI I am having the following issue: 

/node_modules/node-microphone/index.js:6
class Microphone {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/git/myapp/app_client_socketio.js:99:11)    //this is where I load 
                                                                                                      //var Mic = require('node-microphone');
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

Do you know what I am doing wrong ?

**Comment by Flowr-es** [comment]
The module is based on es6 features. Which version are you using on your rpi? On 5.10 or higher it works, maybe also on node version 4 but I'm not sure.

**Comment by spoggie** [comment]
That is right I had to update to node 6.5. 
With this new installation it is working like a charm 
Thank you @MexXxo

**Comment by Flowr-es** [comment]
Cool! 
I have added also that node 4 is required  as min version to the module. 
I will also test it soon on my rpi (waiting for my matrix-creator mic array)
